@startuml

actor Student

Student -> UserInterface : 1. login
activate UserInterface

box "Spring Security Framework" #LightBlue
	participant SpringSecurity
end box


UserInterface -> SpringSecurity : 2. check access rights
activate SpringSecurity

note over SpringSecurity
    The user should be
    logged in as a student
    to have access to the
    requested resources
end note

alt successful case

	UserInterface <-- SpringSecurity: 3. user has access rights
	UserInterface -> ApplicationController: 4. getAllApplications()
	activate ApplicationController
	ApplicationController -> ApplicationService: 5. getAllApplications()
	activate ApplicationService
box "Spring Data Framework" #LightBlue
	participant ApplicationRepository
end box
	ApplicationService -> ApplicationRepository: 6. findAll()
	activate ApplicationRepository
	database DB
	ApplicationRepository -> DB: 7. execute sql query
	activate DB
	ApplicationRepository <-- DB : List<Application>
    deactivate DB
    ApplicationService <-- ApplicationRepository: List<Application>
    deactivate ApplicationRepository
    ApplicationController <-- ApplicationService : List<Application>
    deactivate ApplicationService
    UserInterface <-- ApplicationController : List<Application>
    deactivate ApplicationController
    Student <-- UserInterface

else user does not have access rights

	UserInterface <-- SpringSecurity: no access rights
	deactivate SpringSecurity
	Student <-- UserInterface: forbidden
    deactivate UserInterface

else Another type of failure

   Student <- UserInterface:  Please repeat

end
@enduml