@startuml
note right
  User is registered
end note
(*)  --> "User enters username
and password"

if (    Correct login username and password? then
---> [Yes] "User successfully logs in"
--> "Internship applications are displayed"
--> (*)
else
-> [No] "Invalid login username/password"
--> "User enters username
    and password"
Endif

@enduml