@startuml
|System|
|#AntiqueWhite|Company Representative|
start
note right
  User is logged
  in as a company
  representative
end note
:Setup date for interview;

if (has student applied
for the internship?) then (yes)
:choose date and hour;
|System|
:send email notification;

else (no)
Endif

|Company Representative|
stop

@enduml