@startuml

Student -> (View all applications)
Student ---> (Edit profile)
Student ---> (Give feedback)
Student --> (Apply for internship)
Student --> (Search applications)
Student --> (Filter applications)

(Edit profile) --> (Upload CV)
(Edit profile) --> (Edit description)
(Edit profile) --> (Edit skills)
(Edit profile) --> (Upload picture)
(Edit profile) --> (Edit experience)

(Edit skills) --> (Edit rating)

(Edit experience) --> (Edit studies)
(Edit experience) --> (Edit volunteering)
(Edit experience) --> (Edit job)

@enduml